# -*- coding: utf-8 -*-
"""database

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWrmWkfvzh9DtDwFCX3HfnsoGjhewPSe
"""

from flask_mysqldb import MySQL

mysql = MySQL()

def init_db(app):
    app.config['MYSQL_HOST'] = 'localhost'  #host
    app.config['MYSQL_USER'] = 'root'       #user
    app.config['MYSQL_PASSWORD'] = ''  #password
    app.config['MYSQL_DB'] = 'collegemarks'  #name
    mysql.init_app(app)